### ISSUE TITLE
get error when run this project.

### ISSUE THREAD

**Issue by ghost** [blackstar217/rnTest#1]
i followed readme instructions.
But I got error when i run this command `react-native run-ios`
The react-native version I am using is 0.30.0 and the react-native-cli is 1.0.0

version is like under:

```
$ react-native --version
react-native-cli: 1.0.0
react-native: 0.31.0

$ node -v
v6.3.1
```
 :)

**Comment by ninjadev1030** [comment]
hi @blackstar217 
it's me Alexandra.
please write down your email so i can invite you slack.

**Comment by trustme217** [comment]
hi, thanks for your reporting error.

I didn't finish this repo, so please don't use this one
(your native version is very low.)

blackstar_dalian@outlook.com

**Comment by ghost** [comment]
Hi, I am very interested in the repo, so I hope it fixed shortlycheersI guess you are being idle these days...    On Monday, June 25, 2018, 1:51:09 a.m. GMT+8, blackstar217 <notifications@github.com> wrote:  
 
 
hi, thanks for your reporting error.

I didn't finish this repo, so please don't use this one

blackstar_dalian@outlook.com

**Comment by ninjadev1030** [comment]
okay. i see.
if you update this project, let me know.
I'd like to use this template because my project is very similar with this.
And just sent you invitation via $lack and please let's discuss about this problem.
